[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2021"
authors = ["Nicole Lama <nlama@redhat.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.1"
actix-web = "4.9.0"
